import { StyleSheet } from 'react-native';

export const commonStyles = StyleSheet.create({
backButtonTop: {
    position: 'absolute',
    top: 30,
    left: 10,
    width: 45,
    height: 45,
},
arrowIconContainer: {
  position: 'absolute',
  alignSelf: 'flex-start',
  top: 13,
  left: 10,
  height: 24,
  width: 24,
},
searchContainer: {
  position: 'absolute',
  alignSelf: 'center',
  top: '8%',
  width: '45%',
  height: '5.5%',
},
searchIconContainer: {
  position: 'absolute',
  top: 13,
  left: 10,
  height: 24,
  width: 24,
},
searchBar: {
  position: 'absolute',
  alignSelf: 'center',
  width: '100%',
  height: '100%',
  backgroundColor: 'rgba(255, 255, 255, 0.84)',
  borderRadius: 10,
  marginBottom: 10,
  paddingHorizontal: 20,
},
searchTextContainer: {
  position: 'absolute',
  top: '10%',
  left: '20%',
  height: '80%',
  width: '75%',
},

listContainer: {
  position: 'absolute',
  top: '15%',
  width: '100%',
  height: '85%',
  alignItems: 'center',
},
title: {
    position: 'relative',
    alignSelf: 'flex-start',
    left: 20,
    marginBottom: 5,
    fontSize: 18,
    color: 'white',
    fontWeight: 'bold',
  },
line: {
    position: 'relative',
    alignSelf: 'flex-start',
    marginBottom: 15,
    height: 1,
    width: '90%',
    backgroundColor: '#FFFFFF',
  },
listItemContainer: {
    width: 380,
    height: 41,
    backgroundColor: 'rgba(255, 255, 255, 0.74)',
    borderRadius: 10,
    paddingHorizontal: 20,
},
separator: {
  marginVertical: 10,
},
acceptButton: {
    position: 'absolute',
    top: '20%',
    right: '30%',
    width: '20%',
    height: '60%',
    backgroundColor: '#85C1A4',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    borderRadius: 5,
  },
  rejectButton: {
    position: 'absolute',
    top: '20%',
    right: '5%',
    width: '20%',
    height: '60%',
    backgroundColor: '#F87878',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    borderRadius: 5,
  },
  removeButton: {
    position: 'absolute',
    top: '20%',
    right: '5%',
    width: '25%',
    height: '60%',
    backgroundColor: '#F87878',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    borderRadius: 5,
  },
buttonText: {
    fontFamily: 'Arial',
    fontStyle: 'normal',
    fontWeight: '400',
    fontSize: 15,
    lineHeight: 27,
    textAlign: 'center',
    color: '#000000',
},
  usernameText: {
    fontSize: 16,
    top: '-35%',
    left: '10%',
    color: 'black',
  },
  friendIcon: {
    top: '20%',
    height: '70%',
    left: '-2%',
    aspectRatio: 1,
    borderRadius: 100,
  }
});